---
title: "TODO"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{TODO}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

- Objects
  - [x] - A class object attribute, a reference to the class object, and retrieved with `object_class()`.
  - [x] - For S3 compatibility, a class attribute, a character vector of class names.
  - [x] - Additional attributes storing properties defined by the class, accessible with `@/property()`.
- Classes
  - [x] - R7 classes are first class objects with the following
    - [x] - `name`, a human-meaningful descriptor for the class.
    - [x] - `parent`, the class object of the parent class.
    - [x] - A constructor, an user-facing function used to create new objects of this class. It always ends with a call to `new_object()` to initialize the class.
    - [x] - A validator, a function that takes the object and returns NULL if the object is valid, otherwise a character vector of error messages.
    - [x] - properties, a list of property objects
- Initialization
  - [x] - The constructor uses `new_object()` to initialize a new object, this
    - [x] - Inspects the enclosing scope to find the "current" class.
    - [ ] - Creates the prototype, by either by calling the parent constructor or by creating a base type and adding class and `object_class()` attributes to it.
    - [x] - Validates properties then adds to prototype.
    - [x] - Validates the complete object.
- Shortcuts
  - [ ] - any argument that takes a class object can instead take the name of a class object as a string
  - [x] - instead of providing a list of property objects, you can instead provide a named character vector.
- Validation
  - [x] - valid_eventually
  - [x] - valid_implicitly
- Unions
  - [x] - Used in properties to allow a property to be one of a set of classes
  - [x] - In method dispatch as a convenience for defining a method for multiple classes
- Properties
  - [x] - Accessed using `property()` / `property<-`
  - [x] - Accessed using `@` / `@<-`
  - [x] - A name, used to label output
  - [x] - A optional class or union
  - [x] - An optional accessor functions, both getter and setters
  - [x] - Properties are created with `new_property()`
  - [ ] - If a properties define a getter it should not be writable unless there is an explicit setter.
- Generics
  - [x] - It knows its name and the names of the arguments in its signature
  - [x] - Calling `new_generic()` defines a new generic
  - [ ] - By convention, any argument that takes a generic function, can instead take the name of a generic function supplied as a string
- Methods
  - Registration
    - [x] - Methods are defined by calling method<-(generic, signature, method):
    - [x] - generic is a generic function.
    - [x] - signature is a
      - [x] - single class object
      - [x] - a class union
      - [x] - list of class objects/unions
      - [x] - a character vector.
    - [x] - method is a compatible function
    - [x] - `new_method` is designed to work at run-time
      - [x] - `new_method` should optionally take a package version, so the method is only registered if the package is newer than the version.
    - [ ] - Can define methods where one of the arguments is missing
    - [ ] - Can define methods where one of the arguments has any type
  - Dispatch
    - [x] - Dispatch is nested, meaning that if there are multiple arguments in the generic signature, it will dispatch on the first argument, then the second.
    - [x] - A `plot()` generic dispatching on `x`, e.g. ` plot <- function(x) { method(plot, object_class(x))(x) }`
    - [x] - A `publish()` that publishes an object `x` to a destination `y`, dispatching on both arguments, e.g. `publish <- function(x, y, ...) { method(publish, list(object_class(x), object_class(y)))(x, y, ...) }`
    - [x] - `...` is not used for dispatch
    - [x] - R7 generics can dispatch with base type objects
    - [x] - R7 generics can dispatch with S3 objects
    - [x] - R7 generics can dispatch with S4 objects
    - [x] - `next_method()` can dispatch on multiple arguments, avoiding methods that have already been called.
    - [x] - Generics forward promises to methods, so methods can use non-standard evaluation.
- Compatibility
  - S3
    - [x] - Since the class attribute has the same semantics as S3, S3 dispatch should be fully compatible.
    - [x] - The new generics should also be able to handle legacy S3 objects.
    - [x] - `method()` falls back to single argument S3 dispatch if the R7 dispatch fails.
    - [ ] - `method()` uses S3 group generics as well
  - S4
    - [x] - Since the new generics will fallback to S3 dispatch, they should support S4 objects just as S3 generics support them now.
- Documentation
  - [ ] - Generate index pages that list the methods for a generic or the methods with a particular class in their signature
