# Automatically generated by make_wrappers()
# Do not edit by hand

#' @export
`all.equal.S7_object` <- function (target, current, ...) 
{
    if (is.pairlist(target)) {
        method_not_implemented("all.equal", target)
    }
    else {
        NextMethod()
    }
}

#' @export
`anyDuplicated.S7_object` <- function (x, incomparables = FALSE, ...) 
{
    if (is.pairlist(x)) {
        method_not_implemented("anyDuplicated", x)
    }
    else {
        NextMethod()
    }
}

#' @export
`anyNA.S7_object` <- function (x, recursive = FALSE) 
{
    if (is.pairlist(x)) {
        method_not_implemented("anyNA", x)
    }
    else {
        NextMethod()
    }
}

#' @export
`aperm.S7_object` <- function (a, perm, ...) 
{
    if (is.pairlist(a)) {
        method_not_implemented("aperm", a)
    }
    else {
        NextMethod()
    }
}

#' @export
`as.array.S7_object` <- function (x, ...) 
{
    if (is.pairlist(x)) {
        method_not_implemented("as.array", x)
    }
    else {
        NextMethod()
    }
}

#' @export
`as.call.S7_object` <- function (x) 
{
    if (is.pairlist(x)) {
        method_not_implemented("as.call", x)
    }
    else {
        NextMethod()
    }
}

#' @export
`as.character.S7_object` <- function (x, ...) 
{
    if (is.pairlist(x)) {
        method_not_implemented("as.character", x)
    }
    else {
        NextMethod()
    }
}

#' @export
`as.complex.S7_object` <- function (x, ...) 
{
    if (is.pairlist(x)) {
        method_not_implemented("as.complex", x)
    }
    else {
        NextMethod()
    }
}

#' @export
`as.data.frame.S7_object` <- function (x, row.names = NULL, optional = FALSE, ...) 
{
    if (is.pairlist(x)) {
        method_not_implemented("as.data.frame", x)
    }
    else {
        NextMethod()
    }
}

#' @export
`as.Date.S7_object` <- function (x, ...) 
{
    if (is.pairlist(x)) {
        method_not_implemented("as.Date", x)
    }
    else {
        NextMethod()
    }
}

#' @export
`as.double.S7_object` <- function (x, ...) 
{
    if (is.pairlist(x)) {
        method_not_implemented("as.double", x)
    }
    else {
        NextMethod()
    }
}

#' @export
`as.environment.S7_object` <- function (x) 
{
    if (is.pairlist(x)) {
        method_not_implemented("as.environment", x)
    }
    else {
        NextMethod()
    }
}

#' @export
`as.expression.S7_object` <- function (x, ...) 
{
    if (is.pairlist(x)) {
        method_not_implemented("as.expression", x)
    }
    else {
        NextMethod()
    }
}

#' @export
`as.function.S7_object` <- function (x, ...) 
{
    if (is.pairlist(x)) {
        method_not_implemented("as.function", x)
    }
    else {
        NextMethod()
    }
}

#' @export
`as.integer.S7_object` <- function (x, ...) 
{
    if (is.pairlist(x)) {
        method_not_implemented("as.integer", x)
    }
    else {
        NextMethod()
    }
}

#' @export
`as.list.S7_object` <- function (x, ...) 
{
    if (is.pairlist(x)) {
        method_not_implemented("as.list", x)
    }
    else {
        NextMethod()
    }
}

#' @export
`as.logical.S7_object` <- function (x, ...) 
{
    if (is.pairlist(x)) {
        method_not_implemented("as.logical", x)
    }
    else {
        NextMethod()
    }
}

#' @export
`as.matrix.S7_object` <- function (x, ...) 
{
    if (is.pairlist(x)) {
        method_not_implemented("as.matrix", x)
    }
    else {
        NextMethod()
    }
}

#' @export
`as.null.S7_object` <- function (x, ...) 
{
    if (is.pairlist(x)) {
        method_not_implemented("as.null", x)
    }
    else {
        NextMethod()
    }
}

#' @export
`as.numeric.S7_object` <- function (x, ...) 
{
    if (is.pairlist(x)) {
        method_not_implemented("as.numeric", x)
    }
    else {
        NextMethod()
    }
}

#' @export
`as.POSIXct.S7_object` <- function (x, tz = "", ...) 
{
    if (is.pairlist(x)) {
        method_not_implemented("as.POSIXct", x)
    }
    else {
        NextMethod()
    }
}

#' @export
`as.POSIXlt.S7_object` <- function (x, tz = "", ...) 
{
    if (is.pairlist(x)) {
        method_not_implemented("as.POSIXlt", x)
    }
    else {
        NextMethod()
    }
}

#' @export
`as.raw.S7_object` <- function (x) 
{
    if (is.pairlist(x)) {
        method_not_implemented("as.raw", x)
    }
    else {
        NextMethod()
    }
}

#' @export
`as.single.S7_object` <- function (x, ...) 
{
    if (is.pairlist(x)) {
        method_not_implemented("as.single", x)
    }
    else {
        NextMethod()
    }
}

#' @export
`as.table.S7_object` <- function (x, ...) 
{
    if (is.pairlist(x)) {
        method_not_implemented("as.table", x)
    }
    else {
        NextMethod()
    }
}

#' @export
`as.vector.S7_object` <- function (x, mode = "any") 
{
    if (is.pairlist(x)) {
        method_not_implemented("as.vector", x)
    }
    else {
        NextMethod()
    }
}

#' @export
`by.S7_object` <- function (data, INDICES, FUN, ..., simplify = TRUE) 
{
    if (is.pairlist(data)) {
        method_not_implemented("by", data)
    }
    else {
        NextMethod()
    }
}

#' @export
`c.S7_object` <- function (...) 
{
    if (is.pairlist(...)) {
        method_not_implemented("c", ...)
    }
    else {
        NextMethod()
    }
}

#' @export
`cbind.S7_object` <- function (..., deparse.level = 1) 
{
    if (is.pairlist(...)) {
        method_not_implemented("cbind", ...)
    }
    else {
        NextMethod()
    }
}

#' @export
`chol.S7_object` <- function (x, ...) 
{
    if (is.pairlist(x)) {
        method_not_implemented("chol", x)
    }
    else {
        NextMethod()
    }
}

#' @export
`close.S7_object` <- function (con, ...) 
{
    if (is.pairlist(con)) {
        method_not_implemented("close", con)
    }
    else {
        NextMethod()
    }
}

#' @export
`conditionCall.S7_object` <- function (c) 
{
    if (is.pairlist(c)) {
        method_not_implemented("conditionCall", c)
    }
    else {
        NextMethod()
    }
}

#' @export
`conditionMessage.S7_object` <- function (c) 
{
    if (is.pairlist(c)) {
        method_not_implemented("conditionMessage", c)
    }
    else {
        NextMethod()
    }
}

#' @export
`cut.S7_object` <- function (x, ...) 
{
    if (is.pairlist(x)) {
        method_not_implemented("cut", x)
    }
    else {
        NextMethod()
    }
}

#' @export
`determinant.S7_object` <- function (x, logarithm = TRUE, ...) 
{
    if (is.pairlist(x)) {
        method_not_implemented("determinant", x)
    }
    else {
        NextMethod()
    }
}

#' @export
`diff.S7_object` <- function (x, ...) 
{
    if (is.pairlist(x)) {
        method_not_implemented("diff", x)
    }
    else {
        NextMethod()
    }
}

#' @export
`dim<-.S7_object` <- function (x, value) 
{
    if (is.pairlist(x)) {
        method_not_implemented("dim<-", x)
    }
    else {
        NextMethod()
    }
}

#' @export
`dimnames.S7_object` <- function (x) 
{
    if (is.pairlist(x)) {
        method_not_implemented("dimnames", x)
    }
    else {
        NextMethod()
    }
}

#' @export
`dimnames<-.S7_object` <- function (x, value) 
{
    if (is.pairlist(x)) {
        method_not_implemented("dimnames<-", x)
    }
    else {
        NextMethod()
    }
}

#' @export
`droplevels.S7_object` <- function (x, ...) 
{
    if (is.pairlist(x)) {
        method_not_implemented("droplevels", x)
    }
    else {
        NextMethod()
    }
}

#' @export
`duplicated.S7_object` <- function (x, incomparables = FALSE, ...) 
{
    if (is.pairlist(x)) {
        method_not_implemented("duplicated", x)
    }
    else {
        NextMethod()
    }
}

#' @export
`flush.S7_object` <- function (con) 
{
    if (is.pairlist(con)) {
        method_not_implemented("flush", con)
    }
    else {
        NextMethod()
    }
}

#' @export
`format.S7_object` <- function (x, ...) 
{
    if (is.pairlist(x)) {
        method_not_implemented("format", x)
    }
    else {
        NextMethod()
    }
}

#' @export
`getDLLRegisteredRoutines.S7_object` <- function (dll, addNames = TRUE) 
{
    if (is.pairlist(dll)) {
        method_not_implemented("getDLLRegisteredRoutines", dll)
    }
    else {
        NextMethod()
    }
}

#' @export
`is.array.S7_object` <- function (x) 
{
    if (is.pairlist(x)) {
        method_not_implemented("is.array", x)
    }
    else {
        NextMethod()
    }
}

#' @export
`is.finite.S7_object` <- function (x) 
{
    if (is.pairlist(x)) {
        method_not_implemented("is.finite", x)
    }
    else {
        NextMethod()
    }
}

#' @export
`is.infinite.S7_object` <- function (x) 
{
    if (is.pairlist(x)) {
        method_not_implemented("is.infinite", x)
    }
    else {
        NextMethod()
    }
}

#' @export
`is.matrix.S7_object` <- function (x) 
{
    if (is.pairlist(x)) {
        method_not_implemented("is.matrix", x)
    }
    else {
        NextMethod()
    }
}

#' @export
`is.na.S7_object` <- function (x) 
{
    if (is.pairlist(x)) {
        method_not_implemented("is.na", x)
    }
    else {
        NextMethod()
    }
}

#' @export
`is.na<-.S7_object` <- function (x, value) 
{
    if (is.pairlist(x)) {
        method_not_implemented("is.na<-", x)
    }
    else {
        NextMethod()
    }
}

#' @export
`is.nan.S7_object` <- function (x) 
{
    if (is.pairlist(x)) {
        method_not_implemented("is.nan", x)
    }
    else {
        NextMethod()
    }
}

#' @export
`is.numeric.S7_object` <- function (x) 
{
    if (is.pairlist(x)) {
        method_not_implemented("is.numeric", x)
    }
    else {
        NextMethod()
    }
}

#' @export
`isSymmetric.S7_object` <- function (object, ...) 
{
    if (is.pairlist(object)) {
        method_not_implemented("isSymmetric", object)
    }
    else {
        NextMethod()
    }
}

#' @export
`julian.S7_object` <- function (x, ...) 
{
    if (is.pairlist(x)) {
        method_not_implemented("julian", x)
    }
    else {
        NextMethod()
    }
}

#' @export
`kappa.S7_object` <- function (z, ...) 
{
    if (is.pairlist(z)) {
        method_not_implemented("kappa", z)
    }
    else {
        NextMethod()
    }
}

#' @export
`labels.S7_object` <- function (object, ...) 
{
    if (is.pairlist(object)) {
        method_not_implemented("labels", object)
    }
    else {
        NextMethod()
    }
}

#' @export
`length<-.S7_object` <- function (x, value) 
{
    if (is.pairlist(x)) {
        method_not_implemented("length<-", x)
    }
    else {
        NextMethod()
    }
}

#' @export
`levels.S7_object` <- function (x) 
{
    if (is.pairlist(x)) {
        method_not_implemented("levels", x)
    }
    else {
        NextMethod()
    }
}

#' @export
`levels<-.S7_object` <- function (x, value) 
{
    if (is.pairlist(x)) {
        method_not_implemented("levels<-", x)
    }
    else {
        NextMethod()
    }
}

#' @export
`mean.S7_object` <- function (x, ...) 
{
    if (is.pairlist(x)) {
        method_not_implemented("mean", x)
    }
    else {
        NextMethod()
    }
}

#' @export
`merge.S7_object` <- function (x, y, ...) 
{
    if (is.pairlist(x)) {
        method_not_implemented("merge", x)
    }
    else {
        NextMethod()
    }
}

#' @export
`months.S7_object` <- function (x, abbreviate) 
{
    if (is.pairlist(x)) {
        method_not_implemented("months", x)
    }
    else {
        NextMethod()
    }
}

#' @export
`names.S7_object` <- function (x) 
{
    if (is.pairlist(x)) {
        method_not_implemented("names", x)
    }
    else {
        NextMethod()
    }
}

#' @export
`names<-.S7_object` <- function (x, value) 
{
    if (is.pairlist(x)) {
        method_not_implemented("names<-", x)
    }
    else {
        NextMethod()
    }
}

#' @export
`open.S7_object` <- function (con, ...) 
{
    if (is.pairlist(con)) {
        method_not_implemented("open", con)
    }
    else {
        NextMethod()
    }
}

#' @export
`plot.S7_object` <- function (x, y, ...) 
{
    if (is.pairlist(x)) {
        method_not_implemented("plot", x)
    }
    else {
        NextMethod()
    }
}

#' @export
`pretty.S7_object` <- function (x, ...) 
{
    if (is.pairlist(x)) {
        method_not_implemented("pretty", x)
    }
    else {
        NextMethod()
    }
}

#' @export
`qr.S7_object` <- function (x, ...) 
{
    if (is.pairlist(x)) {
        method_not_implemented("qr", x)
    }
    else {
        NextMethod()
    }
}

#' @export
`quarters.S7_object` <- function (x, abbreviate) 
{
    if (is.pairlist(x)) {
        method_not_implemented("quarters", x)
    }
    else {
        NextMethod()
    }
}

#' @export
`rbind.S7_object` <- function (..., deparse.level = 1) 
{
    if (is.pairlist(...)) {
        method_not_implemented("rbind", ...)
    }
    else {
        NextMethod()
    }
}

#' @export
`rep.S7_object` <- function (x, ...) 
{
    if (is.pairlist(x)) {
        method_not_implemented("rep", x)
    }
    else {
        NextMethod()
    }
}

#' @export
`rev.S7_object` <- function (x) 
{
    if (is.pairlist(x)) {
        method_not_implemented("rev", x)
    }
    else {
        NextMethod()
    }
}

#' @export
`row.names.S7_object` <- function (x) 
{
    if (is.pairlist(x)) {
        method_not_implemented("row.names", x)
    }
    else {
        NextMethod()
    }
}

#' @export
`row.names<-.S7_object` <- function (x, value) 
{
    if (is.pairlist(x)) {
        method_not_implemented("row.names<-", x)
    }
    else {
        NextMethod()
    }
}

#' @export
`rowsum.S7_object` <- function (x, group, reorder = TRUE, ...) 
{
    if (is.pairlist(x)) {
        method_not_implemented("rowsum", x)
    }
    else {
        NextMethod()
    }
}

#' @export
`scale.S7_object` <- function (x, center = TRUE, scale = TRUE) 
{
    if (is.pairlist(x)) {
        method_not_implemented("scale", x)
    }
    else {
        NextMethod()
    }
}

#' @export
`seek.S7_object` <- function (con, ...) 
{
    if (is.pairlist(con)) {
        method_not_implemented("seek", con)
    }
    else {
        NextMethod()
    }
}

#' @export
`seq.S7_object` <- function (...) 
{
    if (is.pairlist(...)) {
        method_not_implemented("seq", ...)
    }
    else {
        NextMethod()
    }
}

#' @export
`seq.int.S7_object` <- function (from, to, by, length.out, along.with, ...) 
{
    if (is.pairlist(from)) {
        method_not_implemented("seq.int", from)
    }
    else {
        NextMethod()
    }
}

#' @export
`sequence.S7_object` <- function (nvec, ...) 
{
    if (is.pairlist(nvec)) {
        method_not_implemented("sequence", nvec)
    }
    else {
        NextMethod()
    }
}

#' @export
`solve.S7_object` <- function (a, b, ...) 
{
    if (is.pairlist(a)) {
        method_not_implemented("solve", a)
    }
    else {
        NextMethod()
    }
}

#' @export
`sort.S7_object` <- function (x, decreasing = FALSE, ...) 
{
    if (is.pairlist(x)) {
        method_not_implemented("sort", x)
    }
    else {
        NextMethod()
    }
}

#' @export
`split.S7_object` <- function (x, f, drop = FALSE, ...) 
{
    if (is.pairlist(x)) {
        method_not_implemented("split", x)
    }
    else {
        NextMethod()
    }
}

#' @export
`split<-.S7_object` <- function (x, f, drop = FALSE, ..., value) 
{
    if (is.pairlist(x)) {
        method_not_implemented("split<-", x)
    }
    else {
        NextMethod()
    }
}

#' @export
`subset.S7_object` <- function (x, ...) 
{
    if (is.pairlist(x)) {
        method_not_implemented("subset", x)
    }
    else {
        NextMethod()
    }
}

#' @export
`summary.S7_object` <- function (object, ...) 
{
    if (is.pairlist(object)) {
        method_not_implemented("summary", object)
    }
    else {
        NextMethod()
    }
}

#' @export
`t.S7_object` <- function (x) 
{
    if (is.pairlist(x)) {
        method_not_implemented("t", x)
    }
    else {
        NextMethod()
    }
}

#' @export
`toString.S7_object` <- function (x, ...) 
{
    if (is.pairlist(x)) {
        method_not_implemented("toString", x)
    }
    else {
        NextMethod()
    }
}

#' @export
`transform.S7_object` <- function (`_data`, ...) 
{
    if (is.pairlist(`_data`)) {
        method_not_implemented("transform", `_data`)
    }
    else {
        NextMethod()
    }
}

#' @export
`truncate.S7_object` <- function (con, ...) 
{
    if (is.pairlist(con)) {
        method_not_implemented("truncate", con)
    }
    else {
        NextMethod()
    }
}

#' @export
`unique.S7_object` <- function (x, incomparables = FALSE, ...) 
{
    if (is.pairlist(x)) {
        method_not_implemented("unique", x)
    }
    else {
        NextMethod()
    }
}

#' @export
`units.S7_object` <- function (x) 
{
    if (is.pairlist(x)) {
        method_not_implemented("units", x)
    }
    else {
        NextMethod()
    }
}

#' @export
`units<-.S7_object` <- function (x, value) 
{
    if (is.pairlist(x)) {
        method_not_implemented("units<-", x)
    }
    else {
        NextMethod()
    }
}

#' @export
`weekdays.S7_object` <- function (x, abbreviate) 
{
    if (is.pairlist(x)) {
        method_not_implemented("weekdays", x)
    }
    else {
        NextMethod()
    }
}

#' @export
`with.S7_object` <- function (data, expr, ...) 
{
    if (is.pairlist(data)) {
        method_not_implemented("with", data)
    }
    else {
        NextMethod()
    }
}

#' @export
`within.S7_object` <- function (data, expr, ...) 
{
    if (is.pairlist(data)) {
        method_not_implemented("within", data)
    }
    else {
        NextMethod()
    }
}

#' @export
`xtfrm.S7_object` <- function (x) 
{
    if (is.pairlist(x)) {
        method_not_implemented("xtfrm", x)
    }
    else {
        NextMethod()
    }
}

