on:
  push:
    branches: [main, master, base-R-support]
  pull_request:
    branches: [main, master]

name: r-svn-check

jobs:
  r-svn-check:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:

      - uses: actions/checkout@v3
        with:
          repository: t-kalinowski/r-svn
          ref: S5
          fetch-depth: 100 # must be > 1 for '.github/workflows/svn-info.sh' to work
          path: r-svn

      - uses: actions/checkout@v3
        with:
          repository: t-kalinowski/S7
          ref: base-R-support
          path: S7

      - name: Build docker image (includes all tests)
        run: docker build --tag r-svn:s5 --file S7/.github/r-svn-s7.Dockerfile .
